version: '3'

services:
  nifi:
    build: .
    container_name: nifi
    user: root
    environment:
      - JAVA_HOME=/usr/lib/jvm/jdk-21.0.3-bellsoft-x86_64 # Assurez-vous que ce chemin est correct
      #- NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER=ldap-provider
      #- NIFI_SECURITY_USER_ADMIN=admin
      #- NIFI_SECURITY_USER_ADMIN_PASSWD=admin_password
     
    ports:
      - "8443:8443"
    volumes:
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_conf:/opt/nifi/nifi-current/conf
      #- ./nifi_custom_processors:/opt/nifi/nifi-current/custom_processors
      - ./nifi-python-extensions/extracted_extensions/extensions:/opt/nifi/nifi-current/python_extensions

      
      

  nifi-registry:
    container_name: nifi-registry
    image: 'apache/nifi-registry:2.0.0-M4'
    environment:
      - JAVA_HOME=/usr/lib/jvm/jdk-21.0.3-bellsoft-x86_64  # Assurez-vous que ce chemin est correct
    ports:
      - "18080:18080"
    volumes:
      - nifi_registry_database:/opt/nifi-registry/database
      
    depends_on:
      - nifi

volumes:
  nifi_content_repository:
  nifi_registry_database:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_provenance_repository:
  nifi_logs:
  nifi_state:
  nifi_conf:
  
